<a href="https://colab.research.google.com/github/tiara-salsabila/Materi-Kuliah-Semester-5/blob/main/PM_P4_TiaraSalsabila_2488010045.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import pandas as pd
import io

dummy_csv_data = """usia,pendapatan,pendidikan,kota,membeli
17,500000,SMA,Jogja,Tidak
24,750000,S1,Cirebon,Ya
28,900000,S2,Bandung,Tidak
18,700000,S1,Jogja,Ya
16,550000,SMA,Cirebon,Tidak
29,800000,S2,Bandung,Ya
"""

df = pd.read_csv(io.StringIO(dummy_csv_data))
df.head()

   usia  pendapatan pendidikan     kota membeli
0    17      500000        SMA    Jogja   Tidak
1    24      750000         S1  Cirebon      Ya
2    28      900000         S2  Bandung   Tidak
3    18      700000         S1    Jogja      Ya
4    16      550000        SMA  Cirebon   Tidak

Langkah 1 — Menangani nilai hilang (imputasi median/modus).

In [30]:
df['usia'] = df['usia'].fillna(df['usia'].mean())
df['pendapatan'] = df['pendapatan'].fillna(df['pendapatan'].mean())

Langkah 2 — Memisahkan fitur (X) dan label (y).

In [31]:
X = df.drop(columns=['membeli'])
y = df['membeli']

Langkah 3 — Encoding kategorikal (ordinal & one-hot).

In [32]:
X['pendidikan'] = X['pendidikan'].map({'SMA':0, 'S1':1, 'S2':2})  # ordinal
X = pd.get_dummies(X, columns=['kota'], dtype=int)                # nominal
y = y.map({'Tidak':0, 'Ya':1})

Langkah 4 — Membagi data (SEBELUM scaling).

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42)

Langkah 5 — Penskalaan (fit pada latih, transform pada latih & uji).

In [34]:
from sklearn.preprocessing import MinMaxScaler
num = ['usia', 'pendapatan', 'pendidikan']
sc = MinMaxScaler()
X_train[num] = sc.fit_transform(X_train[num])
X_test[num] = sc.transform(X_test[num])

display(X_train.describe())

,usia,pendapatan,pendidikan,kota_Bandung,kota_Cirebon,kota_Jogja
count,4.000000,4.000000,4.000000,4.00000,4.00,4.00
mean,0.519231,0.535714,0.625000,0.50000,0.25,0.25
std,0.515538,0.426583,0.478714,0.57735,0.50,0.50
min,0.000000,0.000000,0.000000,0.00000,0.00,0.00
25%,0.115385,0.321429,0.375000,0.00000,0.00,0.00
50%,0.538462,0.571429,0.750000,0.50000,0.00,0.00
75%,0.942308,0.785714,1.000000,1.00000,0.25,0.25
max,1.000000,1.000000,1.000000,1.00000,1.00,1.00

Langkah 6 — Verifikasi: tidak ada nilai hilang, semua numerik, skala seragam.

In [35]:
print("Missing values di X_train:\n", X_train.isnull().sum())

print("\nDeskripsi X_train:")
display(X_train.describe())

Missing values di X_train:
 usia            0
pendapatan      0
pendidikan      0
kota_Bandung    0
kota_Cirebon    0
kota_Jogja      0
dtype: int64

Deskripsi X_train:

,usia,pendapatan,pendidikan,kota_Bandung,kota_Cirebon,kota_Jogja
count,4.000000,4.000000,4.000000,4.00000,4.00,4.00
mean,0.519231,0.535714,0.625000,0.50000,0.25,0.25
std,0.515538,0.426583,0.478714,0.57735,0.50,0.50
min,0.000000,0.000000,0.000000,0.00000,0.00,0.00
25%,0.115385,0.321429,0.375000,0.00000,0.00,0.00
50%,0.538462,0.571429,0.750000,0.50000,0.00,0.00
75%,0.942308,0.785714,1.000000,1.00000,0.25,0.25
max,1.000000,1.000000,1.000000,1.00000,1.00,1.00

Menambahkan kolom kategorikal baru dan menerapkan one-hot encoding

In [36]:
# Contoh jika ada kolom 'status_pekerjaan'
# X = pd.get_dummies(X, columns=['kota', 'status_pekerjaan'], dtype=int)

Jelaskan mengapa fit_transform pada latih tetapi hanya transform pada uji:

fit_transform pada latih agar komputer  belajar untuk menghitung rumus dari data latih, sedangkan agar kunci jawabannya tidak bocol ke soal atau data leakage pada data uji hanya transform saja yang mana hanya boleh numpang diukur menggunakan patokan data latih.

E. Refleksi
1. Mengapa urutan 'split dulu, baru scaling' penting? Data displit dulu agar data uji tidak tercampur ketika komputer menghitung rumus di data latih.
2. Kapan label encoding dan kapan one-hot encoding? Label encoding dipakai untuk kategori yang memiliki urutan atau tingkatan, sedangkan one-hot untuk kategori nomial yang tidak memiliki urutan atau tingkatan.
3. Apa perbedaan normalisasi dan standardisasi? Normalisasi mengubah skala data agar direntang nilai tertentu antara 0 sampai 1, sedangkan standarisasi mengubah distribusi data agar memiliki nilai rata-rata=0 dan standar deviasi=1.